apiVersion: v1beta1
kind: ClusterRoleBinding
metadata:
  name: kiali
  namespace: {{ namespace }}
  labels:
    app: kiali
    version: {{ version_label }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kiali
subjects:
- kind: ServiceAccount
  name: kiali
  namespace: {{ namespace }}
