apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
spec:
  auth:
    strategy: {{ kiali.auth_strategy }}
    istio_namespace: {{ istio.control_plane_namespace }}
    image_name: {{ kiali.image_name }}
    image_pull_policy: {{ kiali.image_pull_policy }}
