- name: Detect Grafana route on OpenShift
  k8s_facts:
    api_version: route.openshift.io/v1
    kind: Route
    name: grafana
    namespace: "{{ kiali_vars.istio_namespace }}"
  register: grafana_route_raw
  when:
  - is_openshift == True

- name: Set Grafana URL from OpenShift route
  set_fact:
    kiali_vars: "{{ kiali_vars | combine({'external_services': {'grafana': {'url': 'http://' + grafana_route_raw['resources'][0]['status']['ingress'][0]['host']}}}, recursive=True) }}"
  when:
  - is_openshift == True
  - grafana_route_raw['resources'][0] is defined
