- name: Detect Jaeger route on OpenShift
  k8s_facts:
    api_version: route.openshift.io/v1
    kind: Route
    name: tracing
    namespace: "{{ kiali_vars.istio_namespace }}"
  register: jaeger_route_raw
  when:
  - is_openshift == True

- name: Set Jaeger URL From OpenShift route
  set_fact:
    kiali_vars: "{{ kiali_vars | combine({'external_services': {'jaeger': {'url': 'http://' + jaeger_route_raw['resources'][0]['status']['ingress'][0]['host']}}}, recursive=True) }}"
  when:
  - is_openshift == True
  - jaeger_route_raw['resources'][0] is defined
