- name: "Create Kiali objects on OpenShift"
  include_tasks: process-resource.yml
  vars:
    process_resource_cluster: "openshift"
  with_items:
  - serviceaccount
  - configmap
  - clusterrole
  - clusterrole-viewer
  - clusterrolebinding
  - deployment
  - service
  - ingress
  - route
  loop_control:
    loop_var: process_resource_item
  when:
  - is_openshift == True

- name: Process Kiali OAuth client on OpenShift
  include: openshift/os-oauth.yml
  when:
  - is_openshift == True
