- name: Detect Jaeger route on OpenShift
  k8s_facts:
    api_version: route.openshift.io/v1
    kind: Route
    name: tracing
    namespace: "{{ istio_namespace }}"
  register: jaeger_route_raw
  when: is_openshift == True

- name: Set Jaeger URL From OpenShift route
  set_fact:
    jaeger_url: "http://{{ jaeger_route_raw['resources'][0]['status']['ingress'][0]['host'] }}"
  when:
  - is_openshift == True
  - jaeger_route_raw['resources'][0] is defined
