apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-extension-metrics-server
  labels:
    app: demo-extension-metrics-server
    app.kubernetes.io/name: demo-extension-metrics-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-extension-metrics-server
  template:
    metadata:
      labels:
        app: demo-extension-metrics-server
        app.kubernetes.io/name: demo-extension-metrics-server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9090"
    spec:
      containers:
      - name: demo-extension-metrics-server
        image: quay.io/kiali/demo-extension-metrics-server:latest
        ports:
        - containerPort: 9090
        env:
        - name: METRICS_PORT
          value: "9090"
        - name: METRICS_FILE
          value: "/tmp/metrics.txt"
        volumeMounts:
        - name: metrics-volume
          mountPath: /tmp/metrics.txt
          subPath: metrics.txt
      volumes:
      - name: metrics-volume
        configMap:
          name: metrics-configmap
      serviceAccountName: default
---
apiVersion: v1
kind: Service
metadata:
  name: demo-extension-metrics-service
  labels:
    app: demo-extension-metrics-server
    app.kubernetes.io/name: demo-extension-metrics-server
spec:
  selector:
    app: demo-extension-metrics-server
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-configmap
data:
  metrics.txt: |
    # HELP kiali_ext_requests_total Total number of requests that have responses
    # TYPE kiali_ext_requests_total counter
    kiali_ext_requests_total{extension="skupper",protocol="http",source_cluster="my-cluster",source_namespace="east",source_service="the-client-svc",source_version="1.0",reporter="source",reporter_id="abcde12345",dest_cluster="west",dest_service="the-db-svc",dest_version="1.0",security="mtls",status_code="200",flags=""} $(shuf -i 5-10 -n 1)
    # HELP kiali_ext_response_time_seconds Amount of seconds before a response was sent back
    # TYPE kiali_ext_response_time_seconds histogram
    kiali_ext_response_time_seconds_bucket{extension="skupper",protocol="http",source_cluster="my-cluster",source_namespace="east",source_service="the-client-svc",source_version="1.0",reporter="source",reporter_id="abcde12345",dest_cluster="west",dest_service="the-db-svc",dest_version="1.0",security="mtls",flags="",le="0.05"} 2
    kiali_ext_response_time_seconds_bucket{extension="skupper",protocol="http",source_cluster="my-cluster",source_namespace="east",source_service="the-client-svc",source_version="1.0",reporter="source",reporter_id="abcde12345",dest_cluster="west",dest_service="the-db-svc",dest_version="1.0",security="mtls",flags="",le="0.1"} 3
    kiali_ext_response_time_seconds_bucket{extension="skupper",protocol="http",source_cluster="my-cluster",source_namespace="east",source_service="the-client-svc",source_version="1.0",reporter="source",reporter_id="abcde12345",dest_cluster="west",dest_service="the-db-svc",dest_version="1.0",security="mtls",flags="",le="0.5"} 5
    kiali_ext_response_time_seconds_bucket{extension="skupper",protocol="http",source_cluster="my-cluster",source_namespace="east",source_service="the-client-svc",source_version="1.0",reporter="source",reporter_id="abcde12345",dest_cluster="west",dest_service="the-db-svc",dest_version="1.0",security="mtls",flags="",le="1"} 8
    kiali_ext_response_time_seconds_bucket{extension="skupper",protocol="http",source_cluster="my-cluster",source_namespace="east",source_service="the-client-svc",source_version="1.0",reporter="source",reporter_id="abcde12345",dest_cluster="west",dest_service="the-db-svc",dest_version="1.0",security="mtls",flags="",le="5"} 12
    kiali_ext_response_time_seconds_bucket{extension="skupper",protocol="http",source_cluster="my-cluster",source_namespace="east",source_service="the-client-svc",source_version="1.0",reporter="source",reporter_id="abcde12345",dest_cluster="west",dest_service="the-db-svc",dest_version="1.0",security="mtls",flags="",le="+Inf"} 17
    kiali_ext_response_time_seconds_sum{extension="skupper",protocol="http",source_cluster="my-cluster",source_namespace="east",source_service="the-client-svc",source_version="1.0",reporter="source",reporter_id="abcde12345",dest_cluster="west",dest_service="the-db-svc",dest_version="1.0",security="mtls",flags=""} 100
    kiali_ext_response_time_seconds_count{extension="skupper",protocol="http",source_cluster="my-cluster",source_namespace="east",source_service="the-client-svc",source_version="1.0",reporter="source",reporter_id="abcde12345",dest_cluster="west",dest_service="the-db-svc",dest_version="1.0",security="mtls",flags=""} 17
    # HELP kiali_ext_tcp_connections_closed_total total tcp connections closed
    # TYPE kiali_ext_tcp_connections_closed_total counter
    kiali_ext_tcp_connections_closed_total{dest_cluster="1389515b-65e6-4218-8d3b-3da179b53f87",dest_name="mongodb-v1",dest_namespace="mongons",extension="skupper",flags="",reporter="combined",reporter_id="skupper-kiali-bridge-89b57f8cd-j66kk",security="plain",source_cluster="e1fc0634-c934-480e-99c9-bb6a0c0eac3b",source_is_root="true",source_name="mongodb-v1",source_namespace="mongoskupperns"} 194
    # HELP kiali_ext_tcp_connections_opened_total total tcp connections opened
    # TYPE kiali_ext_tcp_connections_opened_total counter
    kiali_ext_tcp_connections_opened_total{dest_cluster="1389515b-65e6-4218-8d3b-3da179b53f87",dest_name="mongodb-v1",dest_namespace="mongons",extension="skupper",flags="",reporter="combined",reporter_id="skupper-kiali-bridge-89b57f8cd-j66kk",security="plain",source_cluster="e1fc0634-c934-480e-99c9-bb6a0c0eac3b",source_is_root="true",source_name="mongodb-v1",source_namespace="mongoskupperns"} 194
    # HELP kiali_ext_tcp_received_total total bytes received in a TCP connection
    # TYPE kiali_ext_tcp_received_total counter
    kiali_ext_tcp_received_total{dest_cluster="1389515b-65e6-4218-8d3b-3da179b53f87",dest_name="mongodb-v1",dest_namespace="mongons",extension="skupper",flags="",reporter="combined",reporter_id="skupper-kiali-bridge-89b57f8cd-j66kk",security="plain",source_cluster="e1fc0634-c934-480e-99c9-bb6a0c0eac3b",source_is_root="true",source_name="mongodb-v1",source_namespace="mongoskupperns"} 90792
    # HELP kiali_ext_tcp_sent_total total bytes sent in a TCP connection
    # TYPE kiali_ext_tcp_sent_total counter
    kiali_ext_tcp_sent_total{dest_cluster="1389515b-65e6-4218-8d3b-3da179b53f87",dest_name="mongodb-v1",dest_namespace="mongons",extension="skupper",flags="",reporter="combined",reporter_id="skupper-kiali-bridge-89b57f8cd-j66kk",security="plain",source_cluster="e1fc0634-c934-480e-99c9-bb6a0c0eac3b",source_is_root="true",source_name="mongodb-v1",source_namespace="mongoskupperns"} 101268
