apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: kiali-app-link-{{ kiali_vars.deployment.namespace }}
  labels:
    app: kiali
    version: {{ kiali_vars.deployment.version_label }}
    kialins: {{ kiali_vars.deployment.namespace }}
spec:
  href: {{ kiali_route_url }}
  location: ApplicationMenu
  text: Kiali
{% for namespace in namespaces %}
---
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: kiali-namespace-link-{{ kiali_vars.deployment.namespace }}-{{ namespace }}
  labels:
    app: kiali
    version: {{ kiali_vars.deployment.version_label }}
    kialins: {{ kiali_vars.deployment.namespace }}
spec:
  href: {{ kiali_route_url }}/{{ kiali_vars.server.web_root }}/console/graph/namespaces?namespaces={{ namespace }}
  location: NamespaceDashboard
  text: Open on Kiali
  namespaceDashboard:
    namespaces:
    - {{ namespace }}
{% endfor %}
