apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: kiali-app-link
spec:
  href: {{ kiali_route_url }}
  location: ApplicationMenu
  text: Kiali
{% for namespace in kiali_vars.deployment.accessible_namespaces %}
---
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: "kiali-namespace-{{ namespace }}-link"
spec:
  href: {{ kiali_route_url }}/{{ kiali_vars.server.web_root }}/console/graph/namespaces?namespaces={{ namespace }}
  location: NamespaceDashboard
  text: Open on Kiali
  namespaceDashboard:
    namespaces:
      - {{ namespace }}
{% endfor %}
