apiVersion: v1
kind: Service
metadata:
  name: kiali
  namespace: {{ kiali_vars.deployment.namespace }}
  labels:
    app: kiali
    version: {{ kiali_vars.deployment.version_label }}
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: kiali-cert-secret
spec:
  type: {{ kiali_vars.deployment.service_type }}
  ports:
  - name: tcp
    protocol: TCP
    port: {{ kiali_vars.server.port }}
  selector:
    app: kiali
    version: {{ kiali_vars.deployment.version_label }}
