apiVersion: v1
kind: Service
metadata:
  name: kiali
  namespace: {{ kiali_vars.deployment.namespace }}
  labels:
    app: kiali
    version: {{ kiali_vars.deployment.version_label }}
spec:
  type: NodePort
  ports:
  - name: tcp
    protocol: TCP
    port: {{ kiali_vars.server.port }}
  selector:
    app: kiali
    version: {{ kiali_vars.deployment.version_label }}
