- name: Create Kiali objects on Kubernetes
  include_tasks: process-resource.yml
  vars:
    process_resource_cluster: "kubernetes"
    role_namespace: "{{ kiali_vars.deployment.namespace }}"
  loop:
  - serviceaccount
  - configmap
  - role
  - role-viewer
  - rolebinding
  - deployment
  - service
  - ingress
  loop_control:
    loop_var: process_resource_item
  when:
  - is_k8s == True

- name: Create additional Kiali roles on Kubernetes
  include_tasks: process-additional-roles.yml
  vars:
    process_resource_cluster: "kubernetes"
  loop: "{{ kiali_vars.deployment.accessible_namespaces }}"
  loop_control:
    loop_var: role_namespace
  when:
  - is_k8s == True
  - '"**" not in kiali_vars.deployment.accessible_namespaces'
