- name: "Create Kiali objects on Kubernetes"
  include_tasks: process-resource.yml
  vars:
    process_resource_cluster: "kubernetes"
  with_items:
  - serviceaccount
  - configmap
  - clusterrole
  - clusterrole-viewer
  - clusterrolebinding
  - deployment
  - service
  - ingress
  loop_control:
    loop_var: process_resource_item
  when:
  - is_k8s == True
