apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kiali
  namespace: {{ namespace }}
  labels:
    app: kiali
    version: {{ version_label }}
  annotations:
    nginx.ingress.kubernetes.io/secure-backends: "true"
spec:
  backend:
    serviceName: kiali
    servicePort: {{ server_port }}
