- name: Assert Kiali Configmap has the correct Auth Strategy
  assert:
    that:
    - kiali_configmap.auth.strategy == kiali.auth_strategy


- name: Assert Kiali Configmap has the correct Label Selector
  assert:
    that:
    - kiali_configmap.api.namespaces.label_selector ==  "kiali.io/member-of={{ istio.control_plane_namespace }}"



- name: Assert Kiali Configmap has the correct Istio Namespace
  assert:
    that:
    - kiali_configmap.auth.istio_namespace == istio.control_plane_namespace


- name: Assert Kiali Configmap has the correct Istio Namespace on Auth
  assert:
    that:
    - kiali_configmap.istio_namespace == istio.control_plane_namespace

- name: Assert Kiali Configmap has the correct Custom Prometheus Url
  assert:
    that:
    - kiali_configmap.external_services.prometheus.custom_metrics_url == "http://prometheus.{{ istio.control_plane_namespace }}:9090"



- name: Assert Kiali Configmap has the correct Prometheus Url
  assert:
    that:
    - kiali_configmap.external_services.prometheus.url == "http://prometheus.{{ istio.control_plane_namespace }}:9090"


- name: Assert Kiali Configmap has the correct Grafana Url
  assert:
    that:
    - kiali_configmap.external_services.grafana.in_cluster_url == "http://grafana.{{ istio.control_plane_namespace }}:3000"


- name: Assert Kiali Configmap has the correct Pilot Url Version
  assert:
    that:
    - kiali_configmap.external_services.istio.url_service_version == "http://istio-pilot.{{ istio.control_plane_namespace }}:8080/version"

