apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: kiali-operator-psp
  labels:
    app: kiali-operator
    version: v1.1.0
spec:
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - downwardAPI
  - hostPath
  - secret
  - configMap
  - emptyDir
