apiVersion: v1
kind: ClusterRoleBinding
metadata:
  name: kiali-operator
  labels:
    app: kiali-operator
    version: ${OPERATOR_VERSION_LABEL}
subjects:
- kind: ServiceAccount
  name: kiali-operator
  namespace: ${OPERATOR_NAMESPACE}
roleRef:
  kind: ClusterRole
  # TODO: for now, using full cluster-admin - we should use our own once we figure out all perms we need
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
