- name: Tests
  hosts: localhost
  connection: local
  vars:
    custom_resource: "{{ lookup('template', cr_file_path) | from_yaml }}"
  tasks:
  - import_tasks: ../common/tasks.yml
  - import_tasks: ../asserts/pod_asserts.yml
  - import_tasks: ../asserts/accessible_namespaces_contains.yml
    vars:
      namespace_list: [ '**' ]

  # Test that console links are correct for accessible namespaces of **
  - name: Get app link
    k8s_facts:
      api_version: console.openshift.io/v1
      kind: ConsoleLink
      namespace: "{{ kiali.install_namespace }}"
      name: kiali-app-link
    register: applink

  - name: Assert that console links are correct
    assert:
      that:
      - "{{ applink.resources[0].metadata.name == 'kiali-app-link' }}"

  # change to accessible_namespaces to a fixed list of namespaces
  - k8s:
      state: present
      api_version: v1
      kind: Namespace
      name: consolelinks1
  - k8s:
      state: present
      api_version: v1
      kind: Namespace
      name: consolelinks2
  - k8s:
      state: present
      api_version: v1
      kind: Namespace
      name: noconsolelinks
  - import_tasks: ../common/set_accessible_namespaces_to_list.yml
    vars:
      namespace_list: [ 'istio-system', 'consolelinks1', 'consolelinks2' ]
  - import_tasks: ../common/wait_for_kiali_cr_changes.yml
  - import_tasks: ../common/wait_for_kiali_running.yml
  - import_tasks: ../common/tasks.yml
  - import_tasks: ../asserts/pod_asserts.yml
  - import_tasks: ../asserts/accessible_namespaces_equals.yml
    vars:
      namespace_list: [ 'istio-system', 'consolelinks1', 'consolelinks2' ]

  # Test that console links are correct across namespaces
  - name: Get app link
    k8s_facts:
      api_version: console.openshift.io/v1
      kind: ConsoleLink
      namespace: "{{ kiali.install_namespace }}"
      name: kiali-app-link
    register: applink
  - name: Get links from consolelinks1
    k8s_facts:
      api_version: console.openshift.io/v1
      kind: ConsoleLink
      namespace: consolelinks1
      name: kiali-namespace-consolelinks1-link
    register: consolelink1
  - name: Get links from consolelinks2
    k8s_facts:
      api_version: console.openshift.io/v1
      kind: ConsoleLink
      namespace: consolelinks2
      name: kiali-namespace-consolelinks2-link
    register: consolelink2
  - name: Get links from noconsolelinks
    k8s_facts:
      api_version: console.openshift.io/v1
      kind: ConsoleLink
      namespace: noconsolelinks
    register: noconsolelinks

  - name: Assert that console links are correct
    assert:
      that:
      - "{{ applink.resources[0].metadata.name == 'kiali-app-link' }}"
      - "{{ consolelink1.resources[0].metadata.name == 'kiali-namespace-consolelinks1-link' }}"
      - "{{ consolelink2.resources[0].metadata.name == 'kiali-namespace-consolelinks2-link' }}"
      - "{{ noconsolelinks.resources | length == 0 }}"

  # change to accessible_namespaces by removing consolelinks2 from the list
  - import_tasks: ../common/set_accessible_namespaces_to_list.yml
    vars:
      namespace_list: [ 'istio-system', 'consolelinks1' ]
  - import_tasks: ../common/wait_for_kiali_cr_changes.yml
  - import_tasks: ../common/wait_for_kiali_running.yml
  - import_tasks: ../common/tasks.yml
  - import_tasks: ../asserts/pod_asserts.yml
  - import_tasks: ../asserts/accessible_namespaces_equals.yml
    vars:
      namespace_list: [ 'istio-system', 'consolelinks1' ]

  # Test that console links are correct - note we removed a namespace from accessible_namespaces so the link should be gone
  - name: Get app link
    k8s_facts:
      api_version: console.openshift.io/v1
      kind: ConsoleLink
      namespace: "{{ kiali.install_namespace }}"
      name: kiali-app-link
    register: applink
  - name: Get links from consolelinks1
    k8s_facts:
      api_version: console.openshift.io/v1
      kind: ConsoleLink
      namespace: consolelinks1
      name: kiali-namespace-consolelinks1-link
    register: consolelink1
  - name: Get links from consolelinks2
    k8s_facts:
      api_version: console.openshift.io/v1
      kind: ConsoleLink
      namespace: consolelinks2
    register: consolelink2
  - name: Get links from noconsolelinks
    k8s_facts:
      api_version: console.openshift.io/v1
      kind: ConsoleLink
      namespace: noconsolelinks
    register: noconsolelinks

  - name: Assert that console links are correct
    assert:
      that:
      - "{{ applink.resources[0].metadata.name == 'kiali-app-link' }}"
      - "{{ consolelink1.resources[0].metadata.name == 'kiali-namespace-consolelinks1-link' }}"
      - "{{ consolelink2.resources | length == 0 }}"
      - "{{ noconsolelinks.resources | length == 0 }}"

  # change to accessible_namespaces back to **
  - import_tasks: ../common/set_accessible_namespaces_to_all.yml
  - import_tasks: ../common/wait_for_kiali_cr_changes.yml
  - import_tasks: ../common/wait_for_kiali_running.yml
  - import_tasks: ../common/tasks.yml
  - import_tasks: ../asserts/pod_asserts.yml
  - import_tasks: ../asserts/accessible_namespaces_contains.yml
    vars:
      namespace_list: [ '**' ]

  # Check that console links are back to the way they should be for **
  - name: Get app link
    k8s_facts:
      api_version: console.openshift.io/v1
      kind: ConsoleLink
      namespace: "{{ kiali.install_namespace }}"
      name: kiali-app-link
    register: applink

  - name: Assert that console links are correct
    assert:
      that:
      - "{{ applink.resources[0].metadata.name == 'kiali-app-link' }}"

  # Remove the test namespaces we created earlier
  - k8s:
      state: absent
      api_version: v1
      kind: Namespace
      name: consolelinks1
  - k8s:
      state: absent
      api_version: v1
      kind: Namespace
      name: consolelinks2
  - k8s:
      state: absent
      api_version: v1
      kind: Namespace
      name: noconsolelinks
