- name: "Create resource [{{ process_resource_item}}] on [{{ process_resource_cluster}}]"
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'templates/' + process_resource_cluster + '/' + process_resource_item + '.yaml') }}"
  register: process_resource_result
  until: process_resource_result.result.kind is defined
  retries: 6
  delay: 10
  when:
  - state == "present"

- name: "Delete resource [{{ process_resource_item}}] on [{{ process_resource_cluster}}]"
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'templates/' + process_resource_cluster + '/' + process_resource_item + '.yaml') }}"
  register: process_resource_result
  until: process_resource_result.result == {}
  retries: 6
  delay: 10
  when:
  - state == "absent"
