apiVersion: v1
kind: Template
metadata:
  name: sws-istio-book-info-traffic-generator
  annotations:
    openshift.io/display-name: Swift Sunshine Istio Book Info Traffic Generator
    description: Traffic Generator for Book Istio Example

parameters:
  - name: IMAGE
    description: What docker image should be used
    value: gbaufake/sws-istio-book-info-traffic-generator:1.0

  - name: PRODUCT_PAGE_BASE_ROUTE
    description: What is the PRODUCT_BASE_ROUTE
    value: CHANGEME

  - name: NUMBER_OF_CLIENTS
    description: Number of Clients
    value: "10"

  - name: MILLISECONDS_REQUEST
    description: Define how many seconds the application needs to wait until the next request
    value: "1000"


objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: sws-istio-book-info-traffic-generator
    labels:
      app: sws-istio-book-info-traffic-generator
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: sws-istio-book-info-traffic-generator
      spec:
        containers:
        - image: gbaufake/sws-istio-book-info-traffic-generator:1.0
          name: sws-istio-book-info-traffic-generator
          imagePullPolicy: Always
          env:
          - name: NUMBER_OF_CLIENTS
            value: ${NUMBER_OF_CLIENTS}

          - name: PRODUCT_PAGE_BASE_ROUTE
            value: ${PRODUCT_PAGE_BASE_ROUTE}

          - name: MILLISECONDS_REQUEST
            value: ${MILLISECONDS_REQUEST}
