---
dependency:
  name: galaxy
platforms:
- name: default
  groups:
  - k8s
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: junit
  playbooks:
    destroy: ../default/destroy.yml
    prepare: ../default/prepare.yml
  inventory:
    group_vars:
      all:
        istio:
          control_plane_namespace: istio-system
        kiali:
          cr_path: 'kiali-cr.yaml'
          accessible_namespaces: 
          - "default"
          - "istio-system"
          operator_namespace: kiali-operator
          operator_image: quay.io/kiali/kiali-operator:latest
          auth_strategy: openshift
          image_name: quay.io/kiali/kiali
          label_selector: kiali.io/member-of={{ istio.control_plane_namespace }}
          image_version: v0.21.0
          image_pull_policy: Always
scenario:
  name: multi-tenancy
  test_sequence:
    - prepare
    - converge
    - destroy