apiVersion: v1
kind: ClusterRoleBinding
metadata:
  name: kiali
  labels:
    app: kiali
    version: ${VERSION_LABEL}
roleRef:
  name: kiali
subjects:
- kind: ServiceAccount
  name: kiali
  namespace: ${NAMESPACE}
