apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  labels:
    app: kiali
    version: ${VERSION_LABEL}
data:
  config.yaml: |
    server:
      port: 20001
      static_content_root_directory: /opt/kiali/console
    external_services:
      istio:
        istio_version_supported: [">= 1.0", ">= 0.1.0"]
      jaeger:
        url: ${JAEGER_URL}
      grafana:
        url: ${GRAFANA_URL}
    identity:
      cert_file: /kiali-cert/tls.crt
      private_key_file: /kiali-cert/tls.key
