apiVersion: oauth.openshift.io/v1
kind: OAuthClient
metadata:
  name: kiali
  labels:
    app: kiali
secret: ${OAUTH_SECRET}
redirectURIs:
  - ${REDIRECT_URL}
  - localhost:3000
grantMethod: auto
allowAnyScope: true
