apiVersion: v1
kind: ServiceAccount
metadata:
  name: kiali-service-account
  labels:
    app: kiali
    version: ${VERSION_LABEL}
  annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"kiali"}}'
