id: sws
kind: Template
apiVersion: v1
name: SWS Template
metadata:
  name: sws
  app: sws
parameters:
- description: The version of the image to use
  name: IMAGE_VERSION
  value: dev
- description: The namespace to use
  name: NAMESPACE
  value: default
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: sws
    labels:
      app: sws
- apiVersion: v1
  kind: Service
  metadata:
    name: sws
    labels:
      app: sws
  parameters:
  spec:
    ports:
      - protocol: TCP
        port: 20001
    selector:
      app: sws
- apiVersion: v1
  kind: Route
  metadata:
    name: sws
    labels:
      app: sws
  spec:
    to:
      kind: Service
      name: sws
- apiVersion: extensions/v1beta1
  kind: DaemonSet
  metadata:
    name: sws
    labels:
      name: sws
      app: sws
  spec:
    selector:
      matchLabels:
        name: sws
    template:
      metadata:
        labels:
          name: sws
          app: sws
      spec:
        serviceAccount: sws
        containers:
        - image: jmazzitelli/sws:${IMAGE_VERSION}
          name: sws
          command:
            - "/opt/sws/sws"
            - "-config"
            - "/sws-configuration/config.yaml"
            - "-v"
            - "5"
          env:
          - name: FOO_STRING
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          volumeMounts:
          - name: sws-configuration
            mountPath: "/sws-configuration"
        volumes:
        - name: sws-configuration
          configMap:
            name: sws-configuration
- apiVersion: v1
  kind: ClusterRole
  metadata:
    name: sws
    labels:
      name: sws
      app: sws
  rules:
  - apiGroups: [""]
    attributeRestrictions: null
    resources:
    - configmaps
    - namespaces
    - nodes
    - pods
    - projects
    - services
    - endpoints
    verbs:
    - get
    - list
    - watch
  - apiGroups: ["config.istio.io"]
    attributeRestrictions: null
    resources:
    - routerules
    verbs:
    - get
    - list
    - watch
- apiVersion: v1
  kind: ClusterRoleBinding
  metadata:
    name: sws
    labels:
      name: sws
      app: sws
  roleRef:
    name: sws
  subjects:
  - kind: ServiceAccount
    name: sws
    namespace: ${NAMESPACE}
