apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  labels:
    app: kiali
    version: ${VERSION_LABEL}
data:
  config.yaml: |
    istio_namespace: ${ISTIO_NAMESPACE}
    server:
      port: ${SERVER_PORT}
      web_root: /kiali
    external_services:
      jaeger:
        url: ${JAEGER_URL}
      grafana:
        url: ${GRAFANA_URL}
    auth:
      strategy: ${AUTH_STRATEGY}
    identity:
      cert_file: /kiali-cert/cert-chain.pem
      private_key_file: /kiali-cert/key.pem
