apiVersion: v1
kind: ServiceAccount
metadata:
  name: kiali${NAME_SUFFIX}
  labels:
    app: kiali
    version: ${VERSION_LABEL}
---
apiVersion: v1
kind: Service
metadata:
  name: kiali${NAME_SUFFIX}
  labels:
    app: kiali
    version: ${VERSION_LABEL}
spec:
  type: NodePort
  ports:
  - name: tcp
    protocol: TCP
    port: 20001
  selector:
    app: kiali
    version: ${VERSION_LABEL}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kiali${NAME_SUFFIX}
  labels:
    app: kiali
    version: ${VERSION_LABEL}
spec:
  backend:
    serviceName: kiali${NAME_SUFFIX}
    servicePort: 20001
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kiali${NAME_SUFFIX}
  labels:
    app: kiali
    version: ${VERSION_LABEL}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiali
      version: ${VERSION_LABEL}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: kiali${NAME_SUFFIX}
      labels:
        app: kiali
        version: ${VERSION_LABEL}
    spec:
      serviceAccount: kiali${NAME_SUFFIX}
      containers:
      - image: ${IMAGE_NAME}:${IMAGE_VERSION}
        name: kiali
        command:
        - "/opt/kiali/kiali"
        - "-config"
        - "/kiali-configuration/config.yaml"
        - "-v"
        - "${VERBOSE_MODE}"
        env:
        - name: ACTIVE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: kiali-configuration
          mountPath: "/kiali-configuration"
      volumes:
      - name: kiali-configuration
        configMap:
          name: kiali${NAME_SUFFIX}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kiali${NAME_SUFFIX}
  labels:
    app: kiali
    version: ${VERSION_LABEL}
rules:
- apiGroups: ["", "apps", "autoscaling"]
  attributeRestrictions: null
  resources:
  - configmaps
  - namespaces
  - nodes
  - pods
  - projects
  - services
  - endpoints
  - deployments
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups: ["config.istio.io"]
  attributeRestrictions: null
  resources:
  - routerules
  - destinationpolicies
  - rules
  - circonuses
  - deniers
  - fluentds
  - kubernetesenvs
  - listcheckers
  - memquotas
  - opas
  - prometheuses
  - rbacs
  - servicecontrols
  - solarwindses
  - stackdrivers
  - statsds
  - stdios
  - apikeys
  - authorizations
  - checknothings
  - kuberneteses
  - listentries
  - logentries
  - metrics
  - quotas
  - reportnothings
  - servicecontrolreports
  verbs:
  - get
  - list
  - watch
- apiGroups: ["networking.istio.io"]
  attributeRestrictions: null
  resources:
  - virtualservices
  - destinationrules
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kiali${NAME_SUFFIX}
  labels:
    app: kiali
    version: ${VERSION_LABEL}
roleRef:
  kind: ClusterRole
  name: kiali${NAME_SUFFIX}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: kiali${NAME_SUFFIX}
  namespace: ${NAMESPACE}
