apiVersion: v1
kind: Secret
metadata:
  name: kiali
  labels:
    app: kiali
    version: ${VERSION_LABEL}
type: Opaque
data:
  username: ${KIALI_USERNAME_BASE64}
  passphrase: ${KIALI_PASSPHRASE_BASE64}