apiVersion: v1
kind: ServiceAccount
metadata:
  name: sws
  labels:
    app: sws
---
apiVersion: v1
kind: Service
metadata:
  name: sws
  labels:
    app: sws
parameters:
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 20001
  selector:
    app: sws
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sws
  labels:
    app: sws
spec:
  backend:
    serviceName: sws
    servicePort: 20001
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: sws
  labels:
    name: sws
    app: sws
spec:
  selector:
    matchLabels:
      name: sws
  template:
    metadata:
      labels:
        name: sws
        app: sws
    spec:
      serviceAccount: sws
      containers:
      - image: jmazzitelli/sws:latest
        name: sws
        command:
          - "/opt/sws/sws"
          - "-config"
          - "/sws-configuration/config.yaml"
          - "-v"
          - "5"
        env:
        - name: FOO_STRING
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: sws-configuration
          mountPath: "/sws-configuration"
      volumes:
      - name: sws-configuration
        configMap:
          name: sws-configuration
