---
dependency:
  name: galaxy
platforms:
- name: test-auth
  groups:
  - k8s
provisioner:
  name: ansible
  options:
    vvv: True
  playbooks:
    destroy: ../default/destroy.yml
    prepare: ../default/prepare.yml
  inventory:
    group_vars:
      all:
        kiali:
          operator_namespace: kiali-operator
          operator_image: quay.io/kiali/kiali-operator:latest
          auth_strategy: openshift
          label_selector: kiali.io/member-of=istio-system
        istio_control_plane_namespace: istio-system
        deploy_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/deploy"
        kiali_cr: 'kiali-cr.yaml'
verifier:
  name: testinfra
  directory: test-auth/tests/
scenario:
  name: test-auth
  test_sequence:
    - prepare
    - converge
    - destroy