- hosts: localhost
  gather_facts: no
  tasks:
  - name: Get Kiali Configmap
    set_fact:
       kiali_configmap: '{{ lookup("k8s", api_version="v1", kind="ConfigMap", namespace="istio-system", resource_name="kiali") }}'


  - name: Format Configmap
    set_fact:
      kiali_configmap: "{{ kiali_configmap.data['config.yaml'] | from_yaml }}"
 

  - name: Assert Kiali Configmap has Openshift
    assert:
      that:
       - kiali_configmap.auth.strategy == "openshift"
       - kiali_configmap.api.namespaces.label_selector == "kiali.io/member-of=istio-system"
       - kiali_configmap.istio_namespace == "istio-system"
