name: Build Frontend

on:
  workflow_call:
    inputs:
      target_branch:
        required: true
        type: string

jobs:
  build_frontend:
    name: Build and unit test frontend
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: yarn
          cache-dependency-path: frontend/yarn.lock

      - name: Build
        run: make clean-all build-ui

      - name: Test frontend
        run: |
          cd frontend
          yarn pretty-quick --check --verbose --branch ${{ inputs.target_branch }}
          yarn test

      - name: Create version file
        run: jq -r '.version' package.json > frontend/build/version.txt

      - name: Upload frontend build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: frontend/build/
