name: Integration Tests Multicluster Backend

on:
  workflow_call:
    inputs:
      target_branch:
        required: true
        type: string
      build_branch:
        required: true
        type: string

env:
  TARGET_BRANCH: ${{ inputs.target_branch }}

jobs:
  integration_tests_backend_multicluster:
    name: Backend API multi-cluster integration tests
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.build_branch }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          # The builtin cache feature ensures that installing golangci-lint
          # is consistently fast.
          cache: true
          cache-dependency-path: go.sum

      - name: Download go binary
        uses: actions/download-artifact@v3
        with:
          name: kiali
          path: ~/go/bin/

      - name: Ensure kiali binary is executable
        run: chmod +x ~/go/bin/kiali

      - name: Download frontend build
        uses: actions/download-artifact@v3
        with:
          name: build
          path: frontend/build

      - name: Run backend integration tests
        run: hack/run-integration-tests.sh --test-suite backend-multi-cluster

      - name: Get debug info when integration tests fail
        if: failure()
        run: |
          kubectl --context kind-east logs -l app.kubernetes.io/name=kiali --tail=-1 --all-containers -n istio-system
          kubectl --context kind-east describe nodes
          kubectl --context kind-east get pods -l app.kubernetes.io/name=kiali -n istio-system -o yaml
          kubectl --context kind-east logs -p deployments/controller -n metallb-system
          kubectl --context kind-east logs -p ds/speaker -n metallb-system
          kubectl --context kind-east logs deployments/controller -n metallb-system
          kubectl --context kind-east logs ds/speaker -n metallb-system
