name: Kiali Go CI

on:
  push:
    branches:
    - master
    - v*.*
  pull_request:
    branches:
    - master
    - v*.*

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.10

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Lint Install
        run: make lint-install

      - name: Verify code linting
        run: make lint

      - name: Build
        run: make clean build

      - name: Test
        run: make test-race
